Add icons — Emacs CN, Cute Doom, Lua, Fortran, GNU Octave
Mstrodl/elcord pull request #80
Opened 2023-04-13 02:09 UTC by Feyorsh

Fixes #79

2023-04-20 03:24 UTC, Mstrodl requested changes

2023-04-20 03:24 UTC, Mstrodl commented on elcord.el
> +									(fortran-mode . "fortran-mode_icon")
Fix indentation pls

2023-05-19 10:52 UTC, skykanin commented
@Feyorsh if you like I can apply the necessary changes in a new PR to get this merged if you don't have the time

2023-05-19 18:53 UTC, skykanin requested changes

2023-05-19 18:53 UTC, skykanin commented on elcord.el
> +									(lua-mode . "lua-mode_icon")
You forgot to fix the indentation here

2023-05-19 18:53 UTC, skykanin commented on elcord.el
> +									(octave-mode . "octave-mode_icon")
and here

2023-05-21 14:16 UTC, Feyorsh commented
Untabify user error 🙃 
Thanks for pointing that out @skykanin, should be good to go now

2023-05-25 18:51 UTC, skykanin approved these changes

2023-06-01 15:45 UTC, merged